### ISSUE TITLE
Mods to Snapshots graph requested

### ISSUE THREAD

**Issue by ejgoldstick** [zacharee/ArcadyanKVD21Control#52]
The Shapshots graph that displays when data logging is activated is very useful; however, a few adjustments and additions would make it even better:

1) Change colors to darker, more visible hues (especially the yellow for 5G RISP)

2) Add SiNR (perhaps by changing the max value on the vertical axis to +10 and placing it on top as a third pair of values visualized)

3) Adding RSSI to the same graph might be hard since it overlaps RSRP, but it could be helpful...

... and it would be nice to indicate the bands in the graph with symbols - or perhaps two curves, one for LTE and one for 5G, with the value extracted from the band (b12 -> 12, n71 -> 71), etc.. but that's a big ask.

4) Changing the length of time expressed by the width of the X Axis would be great (eg., 1 min, 1 hour, 1 day... etc.)

Frankly, none of this diminishes the utility of the tool you constructed in Hint Control... Thanks again!

**Comment by zacharee** [comment]
1.11.0 has some changes to the Snapshots graph:
- Colors in dark and light mode should be more visible and distinct.
- RSSI and SiNR tracking have been added.

I'm not planning on adding band data to the graph, since it's not really a chartable data source. You can convert bands to numbers, but correlating them on a line doesn't really mean anything. I also don't plan on adding too much interactability with the graph, since it's meant to be a simple view of some of the data.

With that said, you can always export the snapshot data as JSON and use whatever tools you want to collate and visualize it. If you're on iOS, the README has a section that tells you how to access the data: https://github.com/zacharee/ArcadyanKVD21Control?tab=readme-ov-file#ios-1.
